#!/bin/sh
echo "Vagrant.configure(2) do |config|" > Vagrantfile
echo "config.vm.box = 'bento/centos-7.1' >> Vagrantfile
echo "config.vm.network 'private_network', ip: '192.168.56.2' >> Vagrantfile
echo "end" >> Vagrantfile
