#!/bin/sh
echo "#!/bin/sh " > start.sh
echo "#curl a001 | bash #step1" >> start.sh
echo "#curl a002 | bash #step2" >> start.sh
echo "echo -- status 002 ok --" >> start.sh
echo -- status 001 ok --
sh start.sh
